---
name: Linux-Statistics
version: 1.16
author:
  - Jonny Schulz
abstract: Collect linux system statistics (deprecated).
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Linux::Statistics:
    file: lib/Linux/Statistics.pm
    version: 1.16
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
